name: 🐛 Bug Report
description: Report a bug
labels: ["bug"]
type: issue_form
body:
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Please describe the issue in detail.
    validations:
      required: true
